name: Api-Spammer
on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check env
        run: |
            sudo apt install nodejs
            npm --version
            node --version
            npm install

      - name: Execute script
        run: node app.js
